version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8npass
      POSTGRES_DB: n8ndb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - varcalsys-network

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: n8n_rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: varcal
      RABBITMQ_DEFAULT_PASS: Admin@123
    ports:
      - "5673:5672"    # AMQP
      - "15673:15672"  # Web UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - varcalsys-network

  n8n:
    image: n8nio/n8n:latest
    restart: always
    ports:
      - "5678:5678"
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8ndb
      DB_POSTGRESDB_USER: n8n
      DB_POSTGRESDB_PASSWORD: n8npass

      N8N_BASIC_AUTH_ACTIVE: "true"
      N8N_BASIC_AUTH_USER: admin
      N8N_BASIC_AUTH_PASSWORD: admin123

      N8N_HOST: n8n.local
      N8N_PORT: 5678
      N8N_SECURE_COOKIE: false
      WEBHOOK_TUNNEL_URL: http://localhost:5678

      # Config MQ se for usar Queue-Mode (opcional)
      # QUEUE_MODE: true
      # QUEUE_TYPE: rabbitmq
      # QUEUE_RABBITMQ_HOST: rabbitmq
      # QUEUE_RABBITMQ_PORT: 5672
      # QUEUE_RABBITMQ_USER: varcal
      # QUEUE_RABBITMQ_PASSWORD: Admin@123
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - varcalsys-network

volumes:
  postgres_data:
  n8n_data:
  rabbitmq_data:

networks:
  varcalsys-network:
    name: varcalsys-network
    driver: bridge
